-- Ventiv.dbo.claims definition

-- Drop table

-- DROP TABLE Ventiv.dbo.claims;

CREATE TABLE Ventiv.dbo.claims (
	as_of date NULL,
	book nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	account_name nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	specialty_program nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	carrier nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	LOB nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	accident_am_or_pm nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	accident_address_1 nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	accident_address_2 nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	accident_address_3 nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	accident_city nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	accident_county nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	accident_department nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	accident_description char(2500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	accident_map nvarchar(200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	accident_postal_code nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	accident_shift nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	accident_state nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	accident_time nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	account_id nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	activity_before_loss nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	address_claimant_address_1 nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	address_claimant_address_2 nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	address_claimant_address_3 nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	address_claimant_city nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	address_claimant_postal_code nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	address_claimant_state nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	alternate_claim_number nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	area_of_accident nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	attorney_representation_date date NULL,
	basel_business_line nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	basel_loss_event_type nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	benefit_state nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	bodily_injury nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	body_ncci nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	captive_os_expense float NULL,
	captive_os_indemnity_bi_pd_coll float NULL,
	captive_os_legal float NULL,
	captive_os_medical_comp float NULL,
	captive_os_other float NULL,
	captive_os_total float NULL,
	captive_paid_expense float NULL,
	captive_paid_indem_bi_pd_coll float NULL,
	captive_paid_legal float NULL,
	captive_paid_medical_comp float NULL,
	captive_paid_other float NULL,
	captive_paid_total float NULL,
	case_type nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	cause nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	cause_ncci nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	claim_deductible float NULL,
	claim_number nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	claim_or_incident nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	claim_stage nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	claim_status nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	claimant_death_date date NULL,
	claimant_first_name char(100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	claimant_last_name nvarchar(100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	claimant_m_i nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	claimant_name nvarchar(85) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	claimant_title nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	claims_made_date date NULL,
	claim_created_date date NULL,
	claim_currency_iso_code nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	claim_last_updated_date_char nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	clash_claim nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	class_code nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	closed_date date NULL,
	construction_defect nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	controverted nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	coverage nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	coverage_code nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	created_by nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	created_by_data_process nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	created_date date NULL,
	created_date_rc_claim date NULL,
	TPA nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	date_suit_filed date NULL,
	date_placed_in_litigation date NULL,
	dates_source_claims_made_date date NULL,
	dates_source_close_date date NULL,
	dates_source_entry_date date NULL,
	dates_source_loss_date date NULL,
	dates_source_reopen_date date NULL,
	dates_source_report_date date NULL,
	days_paid float NULL,
	dde_copy_data_from_ee_record nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	ded_sir_os_expense float NULL,
	ded_sir_os_indemnity_bi_pd_coll float NULL,
	ded_sir_os_legal float NULL,
	ded_sir_os_medical_comp float NULL,
	ded_sir_os_other float NULL,
	ded_sir_os_total float NULL,
	ded_sir_paid_expense float NULL,
	ded_sir_paid_indem_bi_pd_coll float NULL,
	ded_sir_paid_legal float NULL,
	ded_sir_paid_medical_comp float NULL,
	ded_sir_paid_other float NULL,
	ded_sir_paid_total float NULL,
	deductible_description nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	deductible_from_policy nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	descr_amtrust_spoiled_claim_num nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	descriptors_source_body_part nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	descriptors_source_cause nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	descriptors_source_coverage nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	descriptors_source_location nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	descriptors_source_nature nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	descriptors_source_pol_eff_date date NULL,
	descriptors_source_policy_number nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	descriptors_source_policy_period nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	descriptors_source_state nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	descriptors_source_status nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	descriptors_travelers_sai_number nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	descr_travelers_st_paul_pol_num nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	downtime_units nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	driver_age float NULL,
	driver_birth_date date NULL,
	driver_first_name nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	driver_last_name nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	driver_m_i nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	driver_relationship nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	driver_sex nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	driver_title nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	drivers_license_number nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	driver_vehicle_additional_info nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	drivers_first_name nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	employer_notification_date date NULL,
	first_aid_care nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	garage_state nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	gross_incurred_expense float NULL,
	gross_incurred_indem_bi_pd_coll float NULL,
	gross_incurred_legal float NULL,
	gross_incurred_medical_comp float NULL,
	gross_incurred_other float NULL,
	gross_incurred_total float NULL,
	healthcare_address_1 nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	healthcare_address_2 nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	healthcare_city nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	healthcare_phone nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	healthcare_postal_code nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	healthcare_provider_type nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	healthcare_state nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	hire_car_required nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	hospitalized_overnight nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	id_for_data_loads nvarchar(100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	in_litigation nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	information_claimant_age float NULL,
	info_claimant_date_of_birth date NULL,
	information_claimant_gender nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	information_claimant_job_title nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	info_claimant_marital_status nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	info_claimant_phone_number nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	information_email nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	information_employee_id nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	information_employee_status nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	information_employment_end_date date NULL,
	info_employment_start_date date NULL,
	information_hire_date date NULL,
	information_job_termination_date date NULL,
	information_ncci_class_code nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	info_occupation_when_injured nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	information_supervisor_email nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	information_supervisor_name nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	information_tax_id nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	information_tax_id_admin nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	information_wage_amount float NULL,
	information_wage_type nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	initial_reserve float NULL,
	initial_treatment_date date NULL,
	injury_or_illness_description nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	insured_name nvarchar(150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	insured_driver_citation nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	insured_driver_information nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	insured_driver_injured nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	insured_driver_injury_desc nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	insured_vehicle_damage_desc nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	insured_vehicle_damaged nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	insurer_os_expense float NULL,
	insurer_os_indemnity_bi_pd_coll float NULL,
	insurer_os_legal float NULL,
	insurer_os_medical_comp float NULL,
	insurer_os_other float NULL,
	insurer_os_total float NULL,
	insurer_paid_expense float NULL,
	insurer_paid_indem_bi_pd_coll float NULL,
	insurer_paid_legal float NULL,
	insurer_paid_medical_comp float NULL,
	insurer_paid_other float NULL,
	insurer_paid_total float NULL,
	jif_incurred float NULL,
	jif_paid float NULL,
	last_financial_update date NULL,
	last_load_date date NULL,
	last_updated_by nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	last_updated_date date NULL,
	last_worked_date date NULL,
	loss_date date NULL,
	loss_description_code char(100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	lost_days float NULL,
	lot_number nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	managed_care_fees nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	manufactured_date date NULL,
	medical_treatment_sought nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	model_number nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	nature nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	nature_ncci nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	net_incurred_expense float NULL,
	net_incurred_indem_bi_pd_coll float NULL,
	net_incurred_legal float NULL,
	net_incurred_medical_comp float NULL,
	net_incurred_other float NULL,
	net_incurred_total float NULL,
	object_substance_causing_harm nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	occ_severity_code nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	occurrence_lead_claim nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	event_number nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	office_code nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	organization nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	osha_completed_by_rep nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	osha_injury_type nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	osha_privacy nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	osha_recordable nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	osha_rep_phone nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	osha_rep_title nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	part nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	physician_healthcare_name nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	police_professional_liability nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	pol_eff_dt date NULL,
	pol_exp_dt date NULL,
	policy_number nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	policy_record_id float NULL,
	policy_year float NULL,
	primary_insurer_limit nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	product_name nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	program_name nvarchar(100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	property_damage nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	purpose_of_journey nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	ql_case_type nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	recovery_expected_expense float NULL,
	recov_expected_indem_bi_pd_coll float NULL,
	recovery_expected_legal float NULL,
	recovery_expected_medical_comp float NULL,
	recovery_expected_other float NULL,
	recovery_expected_total float NULL,
	recovery_paid float NULL,
	recovery_received_expense float NULL,
	recov_received_indem_bi_pd_coll float NULL,
	recovery_received_legal float NULL,
	recovery_received_medical_comp float NULL,
	recovery_received_other float NULL,
	recovery_received_total float NULL,
	reimbursement nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	reimbursement_amount float NULL,
	reinsurance_recovery float NULL,
	release_to_work_date date NULL,
	reopen_date date NULL,
	reopened nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	report_date date NULL,
	report_lag float NULL,
	restricted_days float NULL,
	return_to_work_date date NULL,
	road_conditions nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	road_type nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	salvage_indicator nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	salvage_recovery float NULL,
	serial_number nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	subro_indicator nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	subro_recovery float NULL,
	suit_date date NULL,
	time_employee_began_work nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	total_incurred_net float NULL,
	total_loss nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	total_outstanding float NULL,
	total_paid float NULL,
	total_paid_net float NULL,
	total_recovery float NULL,
	town_incurred float NULL,
	town_paid float NULL,
	tpa_adjuster nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	treated_in_er nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	user_claim_type_override nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	vehicle_description nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	vehicle_downtime nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	vehicle_make nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	vehicle_model nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	vehicle_number nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	vehicle_tag nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	vehicle_year float NULL,
	vin nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	visibility nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	weather_conditions nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	work_began_am_or_pm nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[year] float NULL,
	claim_last_updated_date date NULL,
	cov_desc varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	cov_desc_detail varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
);

CREATE NONCLUSTERED INDEX [NonClusteredIndex-20230725-090425] ON Ventiv.dbo.claims (  as_of ASC  , book ASC  , carrier ASC  , specialty_program ASC  , organization ASC  , account_name ASC  , LOB ASC  , insured_name ASC  , policy_number ASC  , pol_eff_dt ASC  , claim_number ASC  , loss_date ASC  , report_date ASC  )  
  WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
  ON [PRIMARY ] ;