-- Ventiv.dbo.exposures definition

-- Drop table

-- DROP TABLE Ventiv.dbo.exposures;

CREATE TABLE Ventiv.dbo.exposures (
	as_of date NULL,
	book nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	account_name nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	specialty_program nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	carrier nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	LOB nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	aop_deductible nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	address_1 char(100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	address_2 char(100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	building_limit float NULL,
	building_number nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	city nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	class_code nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	construction nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	construction_class nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	contents_limit float NULL,
	coverage nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	coverage_reference nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	created_by nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	created_by_data_process nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	exposure_created_date date NULL,
	created_date_rc_exp date NULL,
	deductible float NULL,
	deductible_type nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	eq_deductible float NULL,
	eq_limit float NULL,
	endorsement_number float NULL,
	expos_dt date NULL,
	expos_eff_dt date NULL,
	expos_exp_dt date NULL,
	exposure_type nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	expos_yr float NULL,
	final_audit_value nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	flood_deductible float NULL,
	flood_limit float NULL,
	id_for_data_loads char(200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	insured_name nvarchar(150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	last_updated_by nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	last_updated_date date NULL,
	load_notes nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	location_number nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	mac_id nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	nbfu_fire_protection_class nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	number_of_stories nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	occupancy_type nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	organization nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	personal_stock float NULL,
	pol_eff_dt date NULL,
	pol_exp_dt date NULL,
	policy_id_for_data_loads nvarchar(100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	postal_code char(75) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	primary_coverage nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	property_location_postal_code nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	public_protection_class nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	rc_record_id float NULL,
	record_id_sort_order nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	record_id nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	risk_reference nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	segment_product nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	source_file_name nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	policy_number nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	square_footage float NULL,
	insured_state nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	stock float NULL,
	subline_load nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	time_element_limit float NULL,
	unit_number float NULL,
	unit_count float NULL,
	unit_make nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	unit_model nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	unit_model_year float NULL,
	unit_radius nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	unit_territory nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	unit_type nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	vin nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	value float NULL,
	value_currency float NULL,
	vehicle_class nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	wind_method nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	wind_hail_ded_amnt nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	wind_hail_ded_pct nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	wind_hail_exclusion nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	year_built float NULL,
	base_rate float NULL,
	subline_code nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	vehicle_base_zone nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	vehicle_size nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	vehicle_terminal_zone nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	vehicle_use nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	exposures float NULL
);
 CREATE NONCLUSTERED INDEX [NonClusteredIndex-20231215-174057] ON Ventiv.dbo.exposures (  as_of ASC  , book ASC  , carrier ASC  , specialty_program ASC  , organization ASC  , account_name ASC  , LOB ASC  , insured_name ASC  , policy_number ASC  , pol_eff_dt ASC  , pol_exp_dt ASC  , class_code ASC  , expos_dt ASC  , expos_eff_dt ASC  , expos_exp_dt ASC  , expos_yr ASC  , insured_state ASC  , location_number ASC  , building_number ASC  , unit_number ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ] ;