-- Ventiv.dbo.policy definition

-- Drop table

-- DROP TABLE Ventiv.dbo.policy;

CREATE TABLE Ventiv.dbo.policy (
	as_of date NULL,
	book nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	account_name nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	specialty_program nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	carrier nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	LOB nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	apd_premium float NULL,
	axa_broker nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	axa_other_mod_2 float NULL,
	axa_other_mod_3 float NULL,
	axa_other_mod_4 float NULL,
	aggregate_limit float NULL,
	annual_broker_fee float NULL,
	annual_expenses float NULL,
	annual_fees float NULL,
	annual_fronting_charge float NULL,
	annual_gross_total_premium float NULL,
	annual_net_premium float NULL,
	annual_other float NULL,
	assigned_risk nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	auto_liability_premium float NULL,
	billing_code nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	broker nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	ca_territory_credit float NULL,
	class_code_description char(200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	comments char(4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	commission_contribution nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	created_by nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	created_by_data_process nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	policy_created_date date NULL,
	created_date_rc_pol date NULL,
	damage_premises float NULL,
	deductible_limit_aggregate float NULL,
	deductible_limit_amount float NULL,
	deductible_limit_description nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	department_of_transportation_num nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	pol_eff_dt date NULL,
	endorsements_broker_fee float NULL,
	endorsements_expenses float NULL,
	endorsements_fees float NULL,
	endorsements_fronting_charge float NULL,
	endorsements_gross_total_premium float NULL,
	endorsements_net_premium float NULL,
	endorsements_other float NULL,
	equipment_premium float NULL,
	expense_mod float NULL,
	experience_mod float NULL,
	pol_exp_dt date NULL,
	extended_reporting_date date NULL,
	fein nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	uw_company nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	gic_score float NULL,
	governing_class_code nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	id_for_loads nvarchar(100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	insured_address_1 nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	insured_address_2 nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	insured_city nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	insured_name char(150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	insured_state nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	insured_zip nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	insurer_pct float NULL,
	insurer_limit_aggregate float NULL,
	insurer_limit_amount float NULL,
	insurer_limit_description nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	insurer_limit_excess_of float NULL,
	is_this_tax nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	last_updated_by nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	policy_last_updated_date date NULL,
	lead_insurer nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	loss_ratio float NULL,
	mac_id nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	marketing_plan nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	medical_expense nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	model_year float NULL,
	non_admitted_factor nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	occurrence_limit nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	organization nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	account_id nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	original_lob nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	other_mod float NULL,
	package_mod float NULL,
	personal_advertising_injury nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	policy_cancel_date nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	policy_number nvarchar(100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	policy_postal_code nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	policy_renewal nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	policy_state nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	policy_transaction_type nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	policy_trigger nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	policy_year float NULL,
	valen_score nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	primary_coverage nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	processing_layer float NULL,
	product_code nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	product_comp_works nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	program_id nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	program_name_link nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	retro_date date NULL,
	sir_limit_aggregate float NULL,
	sir_limit_amount float NULL,
	schedule_mod float NULL,
	program nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	sub_producer_address nvarchar(100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	sub_producer_commission_char nvarchar(100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	sub_producer nvarchar(100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	sub_producer_number nvarchar(100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	total_broker_fee float NULL,
	total_expenses float NULL,
	total_fees float NULL,
	total_fronting_charge float NULL,
	total_gross_total_premium float NULL,
	total_net_premium float NULL,
	total_other float NULL,
	[type] nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	xlia_score float NULL,
	xls_score float NULL,
	agent_name nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	agent_state_code nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	agent_zip_code nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	aggregate_limit_premops float NULL,
	aggregate_limit_products float NULL,
	branch nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	business_type_code nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	cancel_flag nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	consent_to_rate_flag nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	employee_count_initial float NULL,
	location_count_initial float NULL,
	mod_final float NULL,
	multiline_policy nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	new_renew_flag float NULL,
	policy_vehicles float NULL,
	premium_mininum_flag nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	quote_policy_term_number nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	quote_term_effective_date date NULL,
	rating_factor_experience_liab float NULL,
	rating_factor_experience_pd float NULL,
	rating_tier nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	score_id nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	sic_code nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	term_termination_date date NULL,
	underwriter nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	written_premium_final float NULL,
	written_premium_initial float NULL,
	policy_currency_iso_code nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	original_policy_inception_date date NULL,
	sub_producer_commission float NULL
);
 CREATE NONCLUSTERED INDEX [NonClusteredIndex-20231215-123849] ON Ventiv.dbo.policy (  as_of ASC  , book ASC  , carrier ASC  , specialty_program ASC  , organization ASC  , account_name ASC  , LOB ASC  , account_id ASC  , insured_name ASC  , policy_number ASC  , pol_eff_dt ASC  , pol_exp_dt ASC  , marketing_plan ASC  , governing_class_code ASC  , insured_state ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ] ;